stages:
  - linting
  - testing

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose

black_check:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --config .black .

test:
  stage: testing
  image: python:3.11
  script:
    - pip install -r requirements/dev.txt
    - pip install -r requirements/prod.txt
    - pip install django-debug-toolbar==4.2.0
    - cd lyceum
    - python3 manage.py migrate
    - python3 manage.py test