# Generated by Django 5.0.2 on 2024-02-13 23:31

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.SmallIntegerField(verbose_name="номер задания")),
                ("variant", models.SmallIntegerField(verbose_name="вариант задания")),
                (
                    "image",
                    models.ImageField(upload_to="test_images", verbose_name="фото"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "info",
                    models.FilePathField(
                        path=pathlib.PureWindowsPath(
                            "C:/Users/shrom/OneDrive/Рабочий стол/projects/SkillUp/skillup/files/solutions"
                        ),
                        verbose_name="информация о решении",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=40, verbose_name="название предмета"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(verbose_name="время на прохождение теста")),
                (
                    "tasks",
                    models.FilePathField(
                        path=pathlib.PureWindowsPath(
                            "C:/Users/shrom/OneDrive/Рабочий стол/projects/SkillUp/skillup/files/tasks"
                        ),
                        verbose_name="информация о заданиях",
                    ),
                ),
                (
                    "many_solutions",
                    models.BooleanField(
                        default=False,
                        verbose_name="можно ли пройти тест несколько раз?",
                    ),
                ),
            ],
        ),
    ]
