# Generated by Django 5.0.2 on 2024-02-14 10:30

import django.db.models.deletion
import tasks.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="images",
            name="user",
        ),
        migrations.RemoveField(
            model_name="test",
            name="test_images",
        ),
        migrations.AddField(
            model_name="images",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="tasks.test",
                verbose_name="Тест",
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="info",
            field=models.FilePathField(
                path=tasks.tools.solution_info_path, verbose_name="информация о решении"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="tasks",
            field=models.FilePathField(
                path=tasks.tools.test_tasks_path, verbose_name="информация о заданиях"
            ),
        ),
    ]
