# Generated by Django 5.0.2 on 2024-02-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст обращения")),
                ("email", models.EmailField(max_length=254, verbose_name="почта")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("На проверке", "На проверке"),
                            ("Проверено", "Проверено"),
                        ],
                        default="На проверке",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=40, verbose_name="причина отзыва"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создание"
                    ),
                ),
            ],
        ),
    ]
