# Generated by Django 5.0.2 on 2024-02-13 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedback", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.feedbackreason",
            ),
        ),
        migrations.AddField(
            model_name="feedbackstatuslog",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedback.feedback"
            ),
        ),
    ]
