# Generated by Django 5.0.2 on 2024-02-14 10:17

import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=20, verbose_name="Название группы"),
                ),
                (
                    "solutions",
                    models.FilePathField(
                        path=pathlib.PureWindowsPath(
                            "C:/Users/shrom/OneDrive/Рабочий стол/projects/SkillUp/skillup/files/group_marks"
                        ),
                        verbose_name="Оценки учащихся",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tests", models.ManyToManyField(to="tasks.test")),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="user_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
