# Generated by Django 5.0.2 on 2024-02-14 10:30

import groups.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="solutions",
            field=models.FilePathField(
                path=groups.tools.group_solutions_path, verbose_name="Оценки учащихся"
            ),
        ),
    ]
